"""
api.routes.ask

POST /ask — accepts a free-text prompt and returns a compound signal plus
a human-readable explanation generated by the agent.

Flow:
  user prompt → agent.parse_query() → structured params
              → pipeline.runner.run_pipeline() → scores
              → agent.explain_signal() → AskResponse
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException, Request

logger = logging.getLogger(__name__)

from api.agent import explain_signal, parse_query
from api.schemas import AskRequest, AskResponse, QueryParams
from data.storage.db import get_session, save_score
from pipeline.runner import run_pipeline

router = APIRouter()


@router.post("/ask", response_model=AskResponse)
async def ask(request: Request, body: AskRequest) -> dict:
    """Parse a natural-language prompt and return a pipeline signal + explanation.

    Raises
    ------
    503  : Anthropic client not configured (ANTHROPIC_API_KEY missing).
    400  : Agent could not extract valid query parameters from the prompt.
    500  : Unexpected pipeline failure.
    502  : Agent explanation step failed (non-fatal path returns fallback).
    """
    anthropic_client = getattr(request.app.state, "anthropic_client", None)
    if anthropic_client is None:
        raise HTTPException(
            status_code=503,
            detail="Agent unavailable: ANTHROPIC_API_KEY is not set.",
        )

    config = request.app.state.config

    # ── 1. Parse prompt into structured parameters ────────────────────────────
    try:
        query_params: QueryParams = parse_query(body.prompt, anthropic_client, config)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:
        logger.error("Agent parse failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=502, detail="Agent unavailable. Please try again later."
        ) from exc

    # ── 2. Run pipeline ───────────────────────────────────────────────────────
    try:
        result = run_pipeline(query_params.ticker, query_params.horizon, config)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:
        logger.error("Pipeline error in /ask ticker=%s: %s", query_params.ticker, exc, exc_info=True)
        raise HTTPException(
            status_code=500, detail="An internal error occurred. Please try again later."
        ) from exc

    # ── 2b. Best-effort DB persistence ───────────────────────────────────────
    db_engine = getattr(request.app.state, "db_engine", None)
    if db_engine is not None:
        try:
            with get_session(db_engine) as session:
                save_score(result, session)
        except Exception as exc:
            logger.warning("Failed to persist score: %s", exc)

    # ── 3. Generate explanation (non-fatal — fallback on failure) ─────────────
    try:
        explanation = explain_signal(result, body.prompt, anthropic_client, config)
    except Exception:
        explanation = (
            f"Signal: {result['signal']} "
            f"(compound score {result['compound_score']:.3f})"
        )

    return {
        **result,
        "query_params": query_params.model_dump(),
        "explanation": explanation,
    }
